version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-project
    container_name: my-laravel-app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    networks:
      - mynet
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:8.3.0
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    networks:
      - mynet
    volumes:
      - dbdata:/var/lib/mysql

networks:
  mynet:
    driver: bridge

volumes:
  dbdata:
    driver: local
